### ISSUE TITLE
Documentation for BC provider instalation is confusing

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-cmd-tool#156]
The documentation for BC provider is confusing for someone who just wants to use the cmd-tool. We should provide specific documentation for cmd-tool to avoid confusion.

**Comment by romanstrobl** [comment]
The issue will have to wait for the next release.

**Comment by petrdvorak** [comment]
I would even say the issue is no longer there - we now bundle BC with the application which works with almost any setup these days.
