### ISSUE TITLE
Extend support for dryRun

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-cmd-tool#209]
The `dryRun` parameter is used for signature verification. We should allow its usage in other steps, too, especially in the `SignAndEncryptStep` and `EncryptStep`.

**Comment by romanstrobl** [comment]
Note that this solution will only work for request encryption. For successful request decryption, we would also need to serialise the encryptor state and provide logic to decrypt the data. But this can probably be done as a next step.

**Comment by saalistaja** [comment]
Resolved with #208
