### ISSUE TITLE
JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-cmd-tool#232]
The following error occurs on Java 17 when using the BC provider from fat jar:

```
JCE cannot authenticate the provider BC

java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
	at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:131)
	at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:240)
```

The error seems to be caused by following issue in Spring Boot: https://github.com/spring-projects/spring-boot/issues/28837

**Comment by evgenyigumnov** [comment]
Hi, how do you plan to fix this bug?

**Comment by romanstrobl** [comment]
We plan to wait for Spring Boot project to fix the bug. The workaround is to use Java 15 or older.

**Comment by evgenyigumnov** [comment]
I have the same plan :) But this bug reproduced from 12 to 17 java. As result I have to use 11 java

**Comment by romanstrobl** [comment]
The fixing effort moved to: https://github.com/spring-projects/spring-boot/issues/32106

**Comment by romanstrobl** [comment]
The issue seems to be fixed after migrating to Spring Boot 3, we can close this issue.

**Comment by romanstrobl** [comment]
Reopening issue, it is still present with recent versions of Java 17 and Spring Boot `3.1.3`.

**Comment by banterCZ** [comment]
It seems to me, that it is an issue only in Oracle Java. I was able to reproduce it using
```
java version "21" 2023-09-19 LTS
Java(TM) SE Runtime Environment (build 21+35-LTS-2513)
Java HotSpot(TM) 64-Bit Server VM (build 21+35-LTS-2513, mixed mode, sharing)
```
But not with
```
openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment Homebrew (build 17.0.8.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.8.1+0, mixed mode, sharing)
```
This is in accordance with Wilkinsona's statement https://github.com/spring-projects/spring-boot/issues/28837#issuecomment-1630288133

**Comment by SubhiSingh** [comment]
This bouncycastly signed jar issue has been resolved in java 17.0.10.
https://www.oracle.com/java/technologies/javase/17-0-10-relnotes.html

**Comment by petrdvorak** [comment]
Thank you, @SubhiSingh - we can retest and if everything is OK, close the issue.

**Comment by romanstrobl** [comment]
We can close the issue, I was not able to reproduce it on Java `17.0.10`.
