### ISSUE TITLE
Use spring-boot-maven-plugin for jar packaging

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-cmd-tool#40]
Currently the `maven-assembly-plugin` is used for packaging the jar.

This approach will not work on JDK9+ where Bouncy castle jar cannot be placed into jre/lib/ext. The security provider jar needs to be signed. We should consider using `spring-boot-maven-plugin` for packaging of the fat jar, so that the Bouncy castle library remains as is.

We should use a regular Main class to start the cmd-tool application to avoid performance overhead of starting a Spring boot application.

See also: https://github.com/wultra/ssl-pinning-tool/issues/8

**Comment by petrdvorak** [comment]
Yes, let's do this.
